/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author tejas
 */
public class EmpReport extends javax.swing.JFrame {

    /**
     * Creates new form EmpReport
     */
    public EmpReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        btnsumofsalary = new javax.swing.JButton();
        btnavgsalary = new javax.swing.JButton();
        btncountemp = new javax.swing.JButton();
        btnminsalary = new javax.swing.JButton();
        btnmaxsalary = new javax.swing.JButton();
        txtmaxsalary = new javax.swing.JTextField();
        txtsumofsalary = new javax.swing.JTextField();
        txtavgsalary = new javax.swing.JTextField();
        txtcountemp = new javax.swing.JTextField();
        txtminsalary = new javax.swing.JTextField();
        btndescending = new javax.swing.JButton();
        btnascending = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablereport = new javax.swing.JTable();
        btnaddDes = new javax.swing.JButton();
        cmbdes = new javax.swing.JComboBox<>();
        btnexit = new javax.swing.JButton();
        btnsalaryinfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsumofsalary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsumofsalary.setText("Sum Of Salary:");
        btnsumofsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumofsalaryActionPerformed(evt);
            }
        });
        jPanel1.add(btnsumofsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 130, 30));

        btnavgsalary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnavgsalary.setText("Avg Salary: ");
        btnavgsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnavgsalaryActionPerformed(evt);
            }
        });
        jPanel1.add(btnavgsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 30));

        btncountemp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btncountemp.setText("Count Emp:");
        btncountemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncountempActionPerformed(evt);
            }
        });
        jPanel1.add(btncountemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 130, 30));

        btnminsalary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnminsalary.setText("Min Salary: ");
        btnminsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminsalaryActionPerformed(evt);
            }
        });
        jPanel1.add(btnminsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, 30));

        btnmaxsalary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnmaxsalary.setText("Max Salary: ");
        btnmaxsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmaxsalaryActionPerformed(evt);
            }
        });
        jPanel1.add(btnmaxsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 30));
        jPanel1.add(txtmaxsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 160, 30));
        jPanel1.add(txtsumofsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 160, 30));
        jPanel1.add(txtavgsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 160, 30));
        jPanel1.add(txtcountemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 160, 30));
        jPanel1.add(txtminsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 160, 30));

        btndescending.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndescending.setText("Emp Descending");
        btndescending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndescendingActionPerformed(evt);
            }
        });
        jPanel1.add(btndescending, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 150, 40));

        btnascending.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnascending.setText("Emp Ascending");
        btnascending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnascendingActionPerformed(evt);
            }
        });
        jPanel1.add(btnascending, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 150, 40));

        tablereport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablereport);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 950, 280));

        btnaddDes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnaddDes.setText("Add Designation: ");
        btnaddDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddDesActionPerformed(evt);
            }
        });
        jPanel1.add(btnaddDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 750, -1, -1));

        cmbdes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(cmbdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 750, 180, -1));

        btnexit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(847, 10, 120, -1));

        btnsalaryinfo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsalaryinfo.setText("Salary Info >>>>>>");
        btnsalaryinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalaryinfoActionPerformed(evt);
            }
        });
        jPanel1.add(btnsalaryinfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 770, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsumofsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumofsalaryActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
            String sql = "SELECT SUM(GS)FROM emp_salaryinfo" ;
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                int id = rs.getInt(1);
                txtsumofsalary.setText(""+id);
            }
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }     
        
    }//GEN-LAST:event_btnsumofsalaryActionPerformed

    private void btncountempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncountempActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
            String sql = "SELECT COUNT(id)FROM emp_salaryinfo" ;
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                int id = rs.getInt(1);
                txtcountemp.setText(""+id);
            }
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }        
    }//GEN-LAST:event_btncountempActionPerformed

    private void btnminsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminsalaryActionPerformed
        // TODO add your handling code here:
        try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
                    String sql = "select min(GS) from emp_salaryinfo";
                    PreparedStatement pst = con.prepareStatement(sql);
                    ResultSet rs = pst.executeQuery();
                    while(rs.next()){
                        int id = rs.getInt(1);
                        txtminsalary.setText(""+id+"/-");
                    }
                    con.close();
                    rs.close();
                    pst.close();
                } catch (Exception ex) {
                    System.out.println("Ex: "+ex.getMessage());
                }
    }//GEN-LAST:event_btnminsalaryActionPerformed

    private void btnmaxsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmaxsalaryActionPerformed
        // TODO add your handling code here:
        try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
                    String sql = "select MAX(GS) from emp_salaryinfo";
                    PreparedStatement pst = con.prepareStatement(sql);
                    ResultSet rs = pst.executeQuery();
                    while(rs.next()){
                        int id = rs.getInt(1);
                        txtmaxsalary.setText(""+id+"/-");
                    }
                    con.close();
                    rs.close();
                    pst.close();
                } catch (Exception ex) {
                    System.out.println("Ex: "+ex.getMessage());
                }
    }//GEN-LAST:event_btnmaxsalaryActionPerformed

    private void btnascendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnascendingActionPerformed
        // TODO add your handling code here:
        try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1", "root","");
                String sql="select * from emp_salaryinfo order by name asc";
                PreparedStatement pst=con.prepareStatement(sql); 
                ResultSet rs = pst.executeQuery();
                tablereport.setModel(DbUtils.resultSetToTableModel(rs));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                
            }catch(Exception ex)
            {
                System.out.println("Ex"+ex);
            }
    }//GEN-LAST:event_btnascendingActionPerformed

    private void btndescendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndescendingActionPerformed
        // TODO add your handling code here:
         try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1", "root","");
                String sql="select * from emp_salaryinfo order by name desc";
                PreparedStatement pst=con.prepareStatement(sql); 
                ResultSet rs = pst.executeQuery();
                tablereport.setModel(DbUtils.resultSetToTableModel(rs));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                
            }catch(Exception ex)
            {
                System.out.println("Ex"+ex);
            }
    }//GEN-LAST:event_btndescendingActionPerformed

    private void btnavgsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnavgsalaryActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
            String sql = "SELECT AVG(GS)FROM emp_salaryinfo" ;
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                int id = rs.getInt(1);
                txtavgsalary.setText(""+id);
            }
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }     
    }//GEN-LAST:event_btnavgsalaryActionPerformed

    private void btnaddDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddDesActionPerformed
        // TODO add your handling code here:
         try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
            String sql = "SELECT DISTINCT designation FROM emp_salaryinfo";
            PreparedStatement pst  = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
               String item = rs.getString("designation");
               cmbdes.addItem(item);
            }
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnaddDesActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnsalaryinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalaryinfoActionPerformed
        // TODO add your handling code here:
        EmpSalaryInfo ob = new EmpSalaryInfo();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnsalaryinfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddDes;
    private javax.swing.JButton btnascending;
    private javax.swing.JButton btnavgsalary;
    private javax.swing.JButton btncountemp;
    private javax.swing.JButton btndescending;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnmaxsalary;
    private javax.swing.JButton btnminsalary;
    private javax.swing.JButton btnsalaryinfo;
    private javax.swing.JButton btnsumofsalary;
    private javax.swing.JComboBox<String> cmbdes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablereport;
    private javax.swing.JTextField txtavgsalary;
    private javax.swing.JTextField txtcountemp;
    private javax.swing.JTextField txtmaxsalary;
    private javax.swing.JTextField txtminsalary;
    private javax.swing.JTextField txtsumofsalary;
    // End of variables declaration//GEN-END:variables
}
