/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.jdbc;

/**
 *
 * @author tejas
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
public class EmpSalaryInfo extends javax.swing.JFrame {
    double bs;
    double hra;
    double da;
    double ta;
    double pf;
    double it;
    double ns;
    double gs;

    /** Creates new form EmpSalaryInfo */
    public EmpSalaryInfo() {
        initComponents();
        designation.addItem("-Select Designation-");
        designation.addItem("Manager");
        designation.addItem("Human Resourse");
        designation.addItem("Developer");
        designation.addItem("Jr.developer");
        designation.addItem("Team Leadeer");
    }
    public void Clear(){
        txtid.setText(" ");
        txtname.setText(" ");
        txtbs.setText(" ");
        designation.setSelectedIndex(0);
        txthra.setText(" ");
        txtda.setText(" ");
        txtta.setText(" ");
        txtpf.setText(" ");
        txtit.setText(" ");
        txtns.setText(" ");
        txtgs.setText(" ");
    }
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtbs = new javax.swing.JTextField();
        designation = new javax.swing.JComboBox<>();
        txthra = new javax.swing.JTextField();
        txtda = new javax.swing.JTextField();
        txtta = new javax.swing.JTextField();
        txtpf = new javax.swing.JTextField();
        txtit = new javax.swing.JTextField();
        txtns = new javax.swing.JTextField();
        txtgs = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnupadate = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btndelete = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btnreportpage = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Enter Id: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 53, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Enter Basic Salary: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Employee Designation: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 175, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Enter Name: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 93, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("House Rent Allowance (HRA): ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 212, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Dearness Allowance (DA): ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 247, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Traveling Allowance (TA): ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 282, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Provident Fund (PF):");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 317, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Income Tax (IT): ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 352, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Non-Statutory(NS): ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 392, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Gross-Salary (GS): ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 432, -1, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 112, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 112, -1));

        txtbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbsActionPerformed(evt);
            }
        });
        txtbs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbsKeyReleased(evt);
            }
        });
        jPanel1.add(txtbs, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 127, 112, -1));

        jPanel1.add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 172, 130, -1));
        jPanel1.add(txthra, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 207, 112, -1));
        jPanel1.add(txtda, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 242, 112, -1));
        jPanel1.add(txtta, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 279, 112, -1));
        jPanel1.add(txtpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 314, 112, -1));
        jPanel1.add(txtit, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 349, 112, -1));
        jPanel1.add(txtns, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 389, 112, -1));
        jPanel1.add(txtgs, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 429, 112, -1));

        btnsave.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 74, -1));

        btnupadate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnupadate.setText("Update");
        btnupadate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupadateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupadate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 74, -1));

        btnview.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnview.setText("View");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        jPanel1.add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 500, 80, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 870, 370));

        btndelete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 74, -1));

        btnsearch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 100, -1));

        btnnew.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        jPanel1.add(btnnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 74, -1));

        btnreportpage.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnreportpage.setText("Report Info >>>>>");
        btnreportpage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreportpageActionPerformed(evt);
            }
        });
        jPanel1.add(btnreportpage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 510, -1, -1));

        btnexit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, 80, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbsActionPerformed
        // TODO add your handling code here:
       
      
    }//GEN-LAST:event_txtbsActionPerformed

    private void txtbsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbsKeyReleased
        // TODO add your handling code here:
        try{
            bs=Double.parseDouble(txtbs.getText());
            hra=2000.0;
            da=1500.0;
            ta = 1500.0;
            pf = 1700.0;
            it = 200.0;
            ns = 800.0;
            gs=hra+da+bs+ta-pf-it-ns;
            
            txtda.setText(String.valueOf(da));
            txtta.setText(String.valueOf(ta));
            txtpf.setText(String.valueOf(pf));
            txtit.setText(String.valueOf(it));
            txtns.setText(String.valueOf(ns));
            txthra.setText(String.valueOf(hra));
            txtgs.setText(String.valueOf(gs));
            
          
          
        }catch(Exception ex)
        {
            System.out.println("Ex: "+ex.getMessage());
        }
    }//GEN-LAST:event_txtbsKeyReleased

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
       
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
            String sql = "insert into emp_salaryinfo(id,name,basic,designation,HRA,DA,TA,PF,IT,NS,GS) values ('"+txtid.getText()+"','"+txtname.getText()+"','"+txtbs.getText()+"','"+designation.getSelectedItem()+"','"+txthra.getText()+"','"+txtda.getText()+"','"+txtta.getText()+"','"+txtpf.getText()+"','"+txtit.getText()+"','"+txtns.getText()+"','"+txtgs.getText()+"')";
            PreparedStatement pst = con.prepareStatement(sql);
            int i = pst.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"Row Inserted Successfully");
            }
            else{
                JOptionPane.showMessageDialog(null,"Row Not Inserted");
            }
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }
       
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
                    String sql = "select MAX(id) from emp_salaryinfo";
                    PreparedStatement pst = con.prepareStatement(sql);
                    ResultSet rs = pst.executeQuery();
                    while(rs.next()){
                        int id = rs.getInt(1)+1;
                        txtid.setText(""+id);
                    }
                    con.close();
                    rs.close();
                    pst.close();
                } catch (Exception ex) {
                    System.out.println("Ex: "+ex.getMessage());
                }
        txtname.setText(" ");
        txtbs.setText(" ");
        designation.setSelectedIndex(0);
        txthra.setText(" ");
        txtda.setText(" ");
        txtta.setText(" ");
        txtpf.setText(" ");
        txtit.setText(" ");
        txtns.setText(" ");
        txtgs.setText(" ");
                
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnupadateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupadateActionPerformed
        // TODO add your handling code here:
        try {
             Class.forName("com.mysql.jdbc.Driver");
             Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
             String sql="Update emp_salaryinfo set name='"+txtname.getText()+"',basic='"+txtbs.getText()+"',designation='"+designation.getSelectedItem()+"',HRA='"+txthra.getText()+"',DA='"+txtda.getText()+"',TA='"+txtta.getText()+"',PF='"+txtpf.getText()+"',IT='"+txtit.getText()+"',NS='"+txtns.getText()+"',GS ='"+txtgs.getText()+"' where id='"+txtid.getText()+"'";
             PreparedStatement pst=con.prepareStatement(sql);
             int respond = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Update Data?");
             if(respond == JOptionPane.YES_OPTION){
                 int i=pst.executeUpdate();
                 if(i>0){
                     JOptionPane.showMessageDialog(null,"Record Updated sucessfully");
                     Clear();
                    }
                }
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnupadateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1", "root", "");
            String sql = "Select * from emp_salaryinfo where id ='"+txtid.getText()+"'";
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            boolean status = false;
            while(rs.next()){
                 txtname.setText(rs.getString("name"));
                 txtbs.setText(rs.getString("basic"));
                 designation.setSelectedItem(rs.getString("designation"));
                 txthra.setText(rs.getString("HRA"));
                 txtda.setText(rs.getString("DA"));
                 txtta.setText(rs.getString("TA"));
                 txtpf.setText(rs.getString("PF"));
                 txtit.setText(rs.getString("IT"));
                 txtns.setText(rs.getString("NS"));
                 txtgs.setText(rs.getString("gs"));
                 
                 status = true;
            }
            if(!status){
                JOptionPane.showMessageDialog(null,"Record Not Found");
                Clear();
            }
            
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
            String sql = "delete from emp_salaryinfo where id = '"+txtid.getText()+"'";
            PreparedStatement pst  = con.prepareStatement(sql);
            int respond  = JOptionPane.showConfirmDialog(null,"Are you sure to delete a data");
            if(respond == JOptionPane.YES_OPTION){
                int i  = pst.executeUpdate();
                if(i>0){
                    JOptionPane.showMessageDialog(null,"Record Delete Successfully");
                    Clear();
                }
            }
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con  = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_test1","root","");
            String sql = "select * from emp_salaryinfo";
            PreparedStatement pst  = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }
    }//GEN-LAST:event_btnviewActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
      
        try {
            TableModel model = table.getModel();
            int row = table.getSelectedRow();
            int id = (int) table.getValueAt(row,0);
            txtid.setText(""+id);
            String name = (String) table.getValueAt(row, 1);
            txtname.setText(""+name);
            double basic = (double) table.getValueAt(row, 2);
            txtbs.setText(String.valueOf(basic));
            String des = (String) table.getValueAt(row, 3);
            designation.setSelectedItem(""+des);
            String hra  = (String) table.getValueAt(row, 4);
            txthra.setText(""+hra);
            String da  = (String) table.getValueAt(row, 5);
            txtda.setText(""+da);
            String ta  = (String) table.getValueAt(row, 6);
            txtta.setText(""+ta);
            String pf  = (String) table.getValueAt(row, 7);
            txtpf.setText(""+pf);
            String it  = (String) table.getValueAt(row, 8);
            txtit.setText(""+it);
            String ns  = (String) table.getValueAt(row, 9);
            txtns.setText(""+ns);
            String gs  = (String) table.getValueAt(row, 10);
            txtgs.setText(""+gs);
        } catch (Exception ex) {
            System.out.println("Ex: "+ex.getMessage());
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btnreportpageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreportpageActionPerformed
        // TODO add your handling code here:
        EmpReport ob = new EmpReport();
            ob.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_btnreportpageActionPerformed

    private void tableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableMouseReleased

    private void tableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMousePressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tableMousePressed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpSalaryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpSalaryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpSalaryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpSalaryInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpSalaryInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnreportpage;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupadate;
    private javax.swing.JButton btnview;
    private javax.swing.JComboBox<String> designation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtbs;
    private javax.swing.JTextField txtda;
    private javax.swing.JTextField txtgs;
    private javax.swing.JTextField txthra;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtit;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtns;
    private javax.swing.JTextField txtpf;
    private javax.swing.JTextField txtta;
    // End of variables declaration//GEN-END:variables

}
